@extends('layouts.master')
@section('title', __('tools.tools'))

@section('content')

{{-- <div class="preloader"></div> --}}

<div class="wrapper">

	@include('shared.sidenav')

	<div id="content">
		{{-- @include('shared.navbar') --}}

		<div class="container-fluid bg dashboard p20">
			<div class="container-full mt50">
			    <div class="row">
			    	<div class="col-sm-12">
                              <div class="pinned_table table-responsive">
                         		<table class="table">
                         			<thead>
                         				<tr>
                         					<th>one</th>
                         					<th>two</th>
                         					<th>three</th>
                         					<th>adfasdf</th>
                         					<th>asdfasd</th>
                                                      <th>adfsdaf</th>
                                                      <th>adfasdf</th>
                                                      <th>asdfasd</th>
                                                      <th>adf</th>
                                                      <th>asdf</th>
                                                      <th>adfsdaf</th>
                                                      <th>adfasdf</th>
                                                      <th>asdfasd</th>
                                                      <th>adfsdaf</th>
                                                      <th>adfasdf</th>
                                                      <th>asdfasd</th>
                                                      <th>adf</th>
                                                      <th>asdf</th>
                                                      <th>adfsdaf</th>
                                                      <th>adfasdf</th>
                                                      <th>asdfasd</th>
                                                      <th>adfsdaf</th>
                                                      <th>adfasdf</th>
                                                      <th>asdfasd</th>
                         				</tr>
                         			</thead>

                         			<tbody>
                         				<tr>
                         					<td>adskfjalksjf</td>
                         					<td>jkasldf</td>
                         					<td>kljasdlkj</td>
                         					<td>lkjj</td>
                         					<td>lkj</td>
                                                      <td>adsfasdf</td>
                                                      <td>asdf</td>
                                                      <td>porpoepeproeo</td>
                                                      <td>adskfjalksjf</td>
                                                      <td>jkasldf</td>
                                                      <td>kljasdlkj</td>
                                                      <td>lkjj</td>
                                                      <td>lkj</td>
                                                      <td>adsfasdf</td>
                                                      <td>asdf</td>
                                                      <td>porpoepeproeo</td>
                                                      <td>adskfjalksjf</td>
                                                      <td>jkasldf</td>
                                                      <td>kljasdlkj</td>
                                                      <td>lkjj</td>
                                                      <td>lkj</td>
                                                      <td>adsfasdf</td>
                                                      <td>asdf</td>
                                                      <td>porpoepeproeo</td>
                         				</tr>
                         				<tr>
                         					<td>adskfjalksjf</td>
                         					<td>jkasldf</td>
                         					<td>kljasdlkj</td>
                         					<td>lkjj</td>
                         					<td>lkj</td>
                                                      <td>adsfasdf</td>
                                                      <td>asdf</td>
                                                      <td>porpoepeproeo</td>
                                                      <td>adskfjalksjf</td>
                                                      <td>jkasldf</td>
                                                      <td>kljasdlkj</td>
                                                      <td>lkjj</td>
                                                      <td>lkj</td>
                                                      <td>adsfasdf</td>
                                                      <td>asdf</td>
                                                      <td>porpoepeproeo</td>
                                                      <td>adskfjalksjf</td>
                                                      <td>jkasldf</td>
                                                      <td>kljasdlkj</td>
                                                      <td>lkjj</td>
                                                      <td>lkj</td>
                                                      <td>adsfasdf</td>
                                                      <td>asdf</td>
                                                      <td>porpoepeproeo</td>
                         				</tr>
                         				<tr>
                         					<td>adskfjalksjf</td>
                         					<td>jkasldf</td>
                         					<td>kljasdlkj</td>
                         					<td>lkjj</td>
                         					<td>lkj</td>
                                                      <td>adsfasdf</td>
                                                      <td>asdf</td>
                                                      <td>porpoepeproeo</td>
                                                      <td>adskfjalksjf</td>
                                                      <td>jkasldf</td>
                                                      <td>kljasdlkj</td>
                                                      <td>lkjj</td>
                                                      <td>lkj</td>
                                                      <td>adsfasdf</td>
                                                      <td>asdf</td>
                                                      <td>porpoepeproeo</td>
                                                      <td>adskfjalksjf</td>
                                                      <td>jkasldf</td>
                                                      <td>kljasdlkj</td>
                                                      <td>lkjj</td>
                                                      <td>lkj</td>
                                                      <td>adsfasdf</td>
                                                      <td>asdf</td>
                                                      <td>porpoepeproeo</td>
                         				</tr>
                         				<tr>
                         					<td>adskfjalksjf</td>
                         					<td>jkasldf</td>
                         					<td>kljasdlkj</td>
                         					<td>lkjj</td>
                         					<td>lkj</td>
                                                      <td>adsfasdf</td>
                                                      <td>asdf</td>
                                                      <td>porpoepeproeo</td>
                                                      <td>adskfjalksjf</td>
                                                      <td>jkasldf</td>
                                                      <td>kljasdlkj</td>
                                                      <td>lkjj</td>
                                                      <td>lkj</td>
                                                      <td>adsfasdf</td>
                                                      <td>asdf</td>
                                                      <td>porpoepeproeo</td>
                                                      <td>adskfjalksjf</td>
                                                      <td>jkasldf</td>
                                                      <td>kljasdlkj</td>
                                                      <td>lkjj</td>
                                                      <td>lkj</td>
                                                      <td>adsfasdf</td>
                                                      <td>asdf</td>
                                                      <td>porpoepeproeo</td>
                         				</tr>
                         				<tr>
                         					<td>adskfjalksjf</td>
                         					<td>jkasldf</td>
                         					<td>kljasdlkj</td>
                         					<td>lkjj</td>
                         					<td>lkj</td>
                                                      <td>adsfasdf</td>
                                                      <td>asdf</td>
                                                      <td>porpoepeproeo</td>
                                                      <td>adskfjalksjf</td>
                                                      <td>jkasldf</td>
                                                      <td>kljasdlkj</td>
                                                      <td>lkjj</td>
                                                      <td>lkj</td>
                                                      <td>adsfasdf</td>
                                                      <td>asdf</td>
                                                      <td>porpoepeproeo</td>
                                                      <td>adskfjalksjf</td>
                                                      <td>jkasldf</td>
                                                      <td>kljasdlkj</td>
                                                      <td>lkjj</td>
                                                      <td>lkj</td>
                                                      <td>adsfasdf</td>
                                                      <td>asdf</td>
                                                      <td>porpoepeproeo</td>
                         				</tr>
                         				<tr>
                         					<td>adskfjalksjf</td>
                         					<td>jkasldf</td>
                         					<td>kljasdlkj</td>
                         					<td>lkjj</td>
                         					<td>lkj</td>
                                                      <td>adsfasdf</td>
                                                      <td>asdf</td>
                                                      <td>porpoepeproeo</td>
                                                      <td>adskfjalksjf</td>
                                                      <td>jkasldf</td>
                                                      <td>kljasdlkj</td>
                                                      <td>lkjj</td>
                                                      <td>lkj</td>
                                                      <td>adsfasdf</td>
                                                      <td>asdf</td>
                                                      <td>porpoepeproeo</td>
                                                      <td>adskfjalksjf</td>
                                                      <td>jkasldf</td>
                                                      <td>kljasdlkj</td>
                                                      <td>lkjj</td>
                                                      <td>lkj</td>
                                                      <td>adsfasdf</td>
                                                      <td>asdf</td>
                                                      <td>porpoepeproeo</td>
                         				</tr>
                                                <tr>
                                                      <td>adskfjalksjf</td>
                                                      <td>jkasldf</td>
                                                      <td>kljasdlkj</td>
                                                      <td>lkjj</td>
                                                      <td>lkj</td>
                                                      <td>adsfasdf</td>
                                                      <td>asdf</td>
                                                      <td>porpoepeproeo</td>
                                                      <td>adskfjalksjf</td>
                                                      <td>jkasldf</td>
                                                      <td>kljasdlkj</td>
                                                      <td>lkjj</td>
                                                      <td>lkj</td>
                                                      <td>adsfasdf</td>
                                                      <td>asdf</td>
                                                      <td>porpoepeproeo</td>
                                                      <td>adskfjalksjf</td>
                                                      <td>jkasldf</td>
                                                      <td>kljasdlkj</td>
                                                      <td>lkjj</td>
                                                      <td>lkj</td>
                                                      <td>adsfasdf</td>
                                                      <td>asdf</td>
                                                      <td>porpoepeproeo</td>
                                                </tr>
                                                <tr>
                                                      <td>adskfjalksjf</td>
                                                      <td>jkasldf</td>
                                                      <td>kljasdlkj</td>
                                                      <td>lkjj</td>
                                                      <td>lkj</td>
                                                      <td>adsfasdf</td>
                                                      <td>asdf</td>
                                                      <td>porpoepeproeo</td>
                                                      <td>adskfjalksjf</td>
                                                      <td>jkasldf</td>
                                                      <td>kljasdlkj</td>
                                                      <td>lkjj</td>
                                                      <td>lkj</td>
                                                      <td>adsfasdf</td>
                                                      <td>asdf</td>
                                                      <td>porpoepeproeo</td>
                                                      <td>adskfjalksjf</td>
                                                      <td>jkasldf</td>
                                                      <td>kljasdlkj</td>
                                                      <td>lkjj</td>
                                                      <td>lkj</td>
                                                      <td>adsfasdf</td>
                                                      <td>asdf</td>
                                                      <td>porpoepeproeo</td>
                                                </tr>
                                                <tr>
                                                      <td>adskfjalksjf</td>
                                                      <td>jkasldf</td>
                                                      <td>kljasdlkj</td>
                                                      <td>lkjj</td>
                                                      <td>lkj</td>
                                                      <td>adsfasdf</td>
                                                      <td>asdf</td>
                                                      <td>porpoepeproeo</td>
                                                      <td>adskfjalksjf</td>
                                                      <td>jkasldf</td>
                                                      <td>kljasdlkj</td>
                                                      <td>lkjj</td>
                                                      <td>lkj</td>
                                                      <td>adsfasdf</td>
                                                      <td>asdf</td>
                                                      <td>porpoepeproeo</td>
                                                      <td>adskfjalksjf</td>
                                                      <td>jkasldf</td>
                                                      <td>kljasdlkj</td>
                                                      <td>lkjj</td>
                                                      <td>lkj</td>
                                                      <td>adsfasdf</td>
                                                      <td>asdf</td>
                                                      <td>porpoepeproeo</td>
                                                </tr>
                                                <tr>
                                                      <td>adskfjalksjf</td>
                                                      <td>jkasldf</td>
                                                      <td>kljasdlkj</td>
                                                      <td>lkjj</td>
                                                      <td>lkj</td>
                                                      <td>adsfasdf</td>
                                                      <td>asdf</td>
                                                      <td>porpoepeproeo</td>
                                                      <td>adskfjalksjf</td>
                                                      <td>jkasldf</td>
                                                      <td>kljasdlkj</td>
                                                      <td>lkjj</td>
                                                      <td>lkj</td>
                                                      <td>adsfasdf</td>
                                                      <td>asdf</td>
                                                      <td>porpoepeproeo</td>
                                                      <td>adskfjalksjf</td>
                                                      <td>jkasldf</td>
                                                      <td>kljasdlkj</td>
                                                      <td>lkjj</td>
                                                      <td>lkj</td>
                                                      <td>adsfasdf</td>
                                                      <td>asdf</td>
                                                      <td>porpoepeproeo</td>
                                                </tr>
                                                <tr>
                                                      <td>adskfjalksjf</td>
                                                      <td>jkasldf</td>
                                                      <td>kljasdlkj</td>
                                                      <td>lkjj</td>
                                                      <td>lkj</td>
                                                      <td>adsfasdf</td>
                                                      <td>asdf</td>
                                                      <td>porpoepeproeo</td>
                                                      <td>adskfjalksjf</td>
                                                      <td>jkasldf</td>
                                                      <td>kljasdlkj</td>
                                                      <td>lkjj</td>
                                                      <td>lkj</td>
                                                      <td>adsfasdf</td>
                                                      <td>asdf</td>
                                                      <td>porpoepeproeo</td>
                                                      <td>adskfjalksjf</td>
                                                      <td>jkasldf</td>
                                                      <td>kljasdlkj</td>
                                                      <td>lkjj</td>
                                                      <td>lkj</td>
                                                      <td>adsfasdf</td>
                                                      <td>asdf</td>
                                                      <td>porpoepeproeo</td>
                                                </tr>
                                                <tr>
                                                      <td>adskfjalksjf</td>
                                                      <td>jkasldf</td>
                                                      <td>kljasdlkj</td>
                                                      <td>lkjj</td>
                                                      <td>lkj</td>
                                                      <td>adsfasdf</td>
                                                      <td>asdf</td>
                                                      <td>porpoepeproeo</td>
                                                      <td>adskfjalksjf</td>
                                                      <td>jkasldf</td>
                                                      <td>kljasdlkj</td>
                                                      <td>lkjj</td>
                                                      <td>lkj</td>
                                                      <td>adsfasdf</td>
                                                      <td>asdf</td>
                                                      <td>porpoepeproeo</td>
                                                      <td>adskfjalksjf</td>
                                                      <td>jkasldf</td>
                                                      <td>kljasdlkj</td>
                                                      <td>lkjj</td>
                                                      <td>lkj</td>
                                                      <td>adsfasdf</td>
                                                      <td>asdf</td>
                                                      <td>porpoepeproeo</td>
                                                </tr>
                         			</tbody>
                         		</table>
                              </div>
	            	</div>
				</div>
			</div>
		</div>
	</div>

@include('shared.notifications_bar')

@endsection

